[package]
cairo-version = "2.5.4"
name = "mancala"
version = "0.6.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate plan && sozo migrate apply && ./scripts/default_auth.sh"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.6.0" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xOkhai"

[tool.dojo.env]
rpc_url = "https://api.cartridge.gg/x/mancala/katana"
# Default account for katana with seed = 0
account_address = "0x376a2485cf61ea0195abad87971e86ae024386549eb5fb8eb383a044c571d36"
private_key = "0x5d61c129f9beecf5acd6c5e53808388add2164b46696fdcc1fd26aef80c1ce6"
world_address = "0x1ee592601cde2eb4147136aadf1f2f07d4519d510e0cd013a4339dd09a1e192"  # Update this line with your world address

[tool.dojo.world]
name = "Mancala"
description = "Mancala is a classic strategy board game reimagined as a decentralized, on-chain experience."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://realmofra.com"

[tool.dojo.world.socials]
x = "https://x.com/realm_of_ra"
github = "https://github.com/realm-of-ra/mancala"
telegram = "https://t.me/+0UKU3P3Eh_s2NTRh"
